name: 'Date of running Workflow'
author: 'Zekeriya AY <zekeriya@zekeriyaay.com>'
description: 'Print date of last running Workflow to Markdown'

inputs:
  # NOT YET DEVELOPED  
  # section:
  #   description: 'The name of the section to be updated in the Markdown'
  #   required: false
  #   default: 'default'
  markdown_file:
    description: 'Path to Markdown file'
    required: false
    default: 'README.md'
  date_format:
    description: 'Allows you to change the format of the date or time displayed'
    required: false
    default: '+"%a  %d %b %Y  %H:%M:%S %Z" -u'

runs:
  using: 'composite'
  steps:
    - name: 'Print date to Markdown file'
      run: date ${{ inputs.date_format }} > ${{ inputs.markdown_file }}
      shell: bash

branding:
  icon: 'clock'
  color: 'red'