name: 'Datetime of Workflow'
author: 'Zekeriya AY'
description: "Allows you show the datetime of workflow on your GitHub profile or project's README"

inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  date_format:
    description: 'Allows you to change the format of the date or time displayed'
    required: false
    default: '%a  %d %b %Y  %H:%M:%S %Z'
  timezone:
    description: 'Timezone Region'
    required: false
    default: 'UTC'
  tag:
    description: 'The name of the tag to be updated in the Markdown'
    required: false
    default: 'DEFAULT-TAG'
  markdown_path:
    description: 'Path to Markdown file'
    required: false
    default: './README.md'
  commit_branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'main'
  commit_username:
    description: 'Username of the user to commit. If nothing is written, the GitHub Bot is used'
    required: false
    default: 'github-actions[bot]'
  commit_email:
    description: 'Email of the user to commit. If nothing is written, the GitHub Bot is used'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_message:
    description: 'Commit message'
    required: false
    default: '🚀 Datetime of Workflow Updated'

runs:
  using: 'composite'
  steps:
    - name: 'Setup Python'
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: 'Install Dependencies'
      run: |
        python3 -m pip install -r requirements.txt
      shell: bash
    - name: 'Execute Python Script'
      run: |
        python3 $GITHUB_ACTION_PATH/script.py --format '${{ inputs.date_format }}' --tag ${{ inputs.tag }} --path ${{ inputs.markdown_path }} --timezone '${{ inputs.timezone }}'
      shell: bash
    - name: 'GitHub Commit & Push'
      uses: actions-js/push@v1.3
      with:
        github_token: ${{ inputs.github_token }}
        author_name: ${{ inputs.commit_username }}
        author_email: ${{ inputs.commit_email }}
        branch: ${{ inputs.commit_branch }}
        message: ${{ inputs.commit_message }}

branding:
  icon: 'calendar'
  color: 'yellow'