name: Test Datetime of Workflow
on:
  push:
    branches: 
      - #dev
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  workflow-datetime:
    name: Update the datetime of workflow in the README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update with Datetime of Workflow
        uses: ZekeriyaAY/workflow-date@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # date_format: '%a  %d %b %Y  %H:%M:%S%Z'
          # timezone: 'UTC'
          # tag: 'DEFAULT-TAG'
          # markdown_path: './README.md'
          commit_branch: 'dev'
          # commit_username: 'github-actions[bot]'
          # commit_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: '🚀 Datetime of Workflow Updated'
